### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by Njasa2k** [Dawn-LX/Causal-VideoGen#1]

**Comment by Dawn-LX** [comment]
The code is still preparing

**Comment by nunbuzor** [comment]
> we will release the code before july 4

any update on the code release?

**Comment by Dawn-LX** [comment]
The code will be released upon the acceptance of our paper

**Comment by olliacc** [comment]
> The code will be released upon the acceptance of our paper

update?

**Comment by Dawn-LX** [comment]
> > The code will be released upon the acceptance of our paper
> 
> update?

hi, we just updated the code
